export enum NotificationType {
  DOCUMENT_APPROVED = 'DOCUMENT_APPROVED',
  DOCUMENT_REJECTED = 'DOCUMENT_REJECTED',
  VISIT_REQUESTED = 'VISIT_REQUESTED',
  VISIT_ACCEPTED = 'VISIT_ACCEPTED',
  VISIT_REJECTED = 'VISIT_REJECTED',
  VISIT_CANCELLED = 'VISIT_CANCELLED',
  VISIT_RESCHEDULED = 'VISIT_RESCHEDULED',
  VISIT_DONE = 'VISIT_DONE',
  LISTING_MODERATED = 'LISTING_MODERATED',
  AGENCY_REQUEST_APPROVED = 'AGENCY_REQUEST_APPROVED',
}
