import { FILTER_OPERATORS } from '../domain/ast/filter/filter-operator';

export const FilterOperator = {
  EQ: FILTER_OPERATORS.EQ,
  NEQ: FILTER_OPERATORS.NEQ,
  GT: FILTER_OPERATORS.GT,
  GTE: FILTER_OPERATORS.GTE,
  LT: FILTER_OPERATORS.LT,
  LTE: FILTER_OPERATORS.LTE,
  IN: FILTER_OPERATORS.IN,
  NOT_IN: FILTER_OPERATORS.NOT_IN,
  BETWEEN: FILTER_OPERATORS.BETWEEN,
  CONTAINS: FILTER_OPERATORS.CONTAINS,
  STARTS_WITH: FILTER_OPERATORS.STARTS_WITH,
  ENDS_WITH: FILTER_OPERATORS.ENDS_WITH,
  IS_NULL: FILTER_OPERATORS.IS_NULL,
  IS_NOT_NULL: FILTER_OPERATORS.IS_NOT_NULL,
} as const;

export type FilterOperator =
  (typeof FilterOperator)[keyof typeof FilterOperator];
