// shared\src\enums\audit-action.enum.ts
export enum AuditAction {
  // USERS
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  UPDATE_OWN_PROFILE = 'UPDATE_OWN_PROFILE',
  RESTORE_USER = 'RESTORE_USER',

  // PROPERTIES
  CREATE_PROPERTY = 'CREATE_PROPERTY',
  UPDATE_PROPERTY = 'UPDATE_PROPERTY',
  DELETE_PROPERTY = 'DELETE_PROPERTY',

  // PUBLICACIONES
  CREATE_PUBLICACION = 'CREATE_PUBLICACION',
  UPDATE_PUBLICACION = 'UPDATE_PUBLICACION',
  DELETE_PUBLICACION = 'DELETE_PUBLICACION',
  PAUSE_PUBLICACION = 'PAUSE_PUBLICACION',
  APPROVE_PUBLICACION = 'APPROVE_PUBLICACION',
  REJECT_PUBLICACION = 'REJECT_PUBLICACION',

  // FAVORITES
  CREATE_FAVORITE = 'CREATE_FAVORITE',
  DELETE_FAVORITE = 'DELETE_FAVORITE',

  // AUTH
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
}