// shared\src\enums\permission.enum.ts
export enum Permission {
  // PUBLICACIONES
  PUBLICACION_READ = "PUBLICACION_READ",
  PUBLICACION_READ_ALL = "PUBLICACION_READ_ALL",
  PUBLICACION_APPROVE = "PUBLICACION_APPROVE",
  PUBLICACION_REJECT = "PUBLICACION_REJECT",
  PUBLICACION_OBSERVE = "PUBLICACION_OBSERVE",
  PUBLICACION_PAUSE = "PUBLICACION_PAUSE",

  // PROPERTIES
  PROPERTY_CREATE = "PROPERTY_CREATE",
  PROPERTY_UPDATE = "PROPERTY_UPDATE",
  PROPERTY_DELETE = "PROPERTY_DELETE",
  PROPERTY_READ_PRIVATE = "PROPERTY_READ_PRIVATE",

  // FAVORITOS
  FAVORITE_CREATE = "FAVORITE_CREATE",

  // USERS
  USER_MANAGE = "USER_MANAGE",
  USER_READ = "USER_READ",
  USER_CREATE = "USER_CREATE",
  USER_UPDATE = "USER_UPDATE",
  USER_RESTORE = "USER_RESTORE",

  // PROFILE
  PROFILE_UPDATE = "PROFILE_UPDATE",

  // UPLOADS
  UPLOAD_CREATE = "UPLOAD_CREATE",
  UPLOAD_DELETE = "UPLOAD_DELETE",
  UPLOAD_READ = "UPLOAD_READ",

  // DOCUMENTOS
  DOCUMENT_UPLOAD = "DOCUMENT_UPLOAD",
  DOCUMENT_REVIEW = "DOCUMENT_REVIEW",
  DOCUMENT_HISTORY = "DOCUMENT_HISTORY",

  // OPERACIONES
  OPERATION_CREATE = "OPERATION_CREATE",
  OPERATION_UPDATE = "OPERATION_UPDATE",
  OPERATION_DELETE = "OPERATION_DELETE",
  OPERATION_RESERVE = "OPERATION_RESERVE",
  OPERATION_PROCESS = "OPERATION_PROCESS",
  OPERATION_FINISH = "OPERATION_FINISH",
  OPERATION_CANCEL = "OPERATION_CANCEL",
}
