// shared\src\enums\permission.enum.ts
export enum Permission {
  // LISTINGS
  LISTING_CREATE = 'LISTING_CREATE',
  LISTING_UPDATE = 'LISTING_UPDATE',
  LISTING_DELETE = 'LISTING_DELETE',

  LISTING_PUBLISH = 'LISTING_PUBLISH',
  LISTING_PAUSE = 'LISTING_PAUSE',
  LISTING_ARCHIVE = 'LISTING_ARCHIVE',

  LISTING_READ_PRIVATE = 'LISTING_READ_PRIVATE',

  LISTING_MODERATE = 'LISTING_MODERATE',
  LISTING_APPROVE = 'LISTING_APPROVE',
  LISTING_REJECT = 'LISTING_REJECT',

  LISTING_MEDIA_UPLOAD = 'LISTING_MEDIA_UPLOAD',
  LISTING_MEDIA_DELETE = 'LISTING_MEDIA_DELETE',

  // FAVORITES
  FAVORITE_CREATE = 'FAVORITE_CREATE',

  // USERS
  USER_MANAGE = 'USER_MANAGE',
  USER_READ = 'USER_READ',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_RESTORE = 'USER_RESTORE',

  // PROFILE
  PROFILE_UPDATE = 'PROFILE_UPDATE',

  // UPLOADS
  UPLOAD_CREATE = 'UPLOAD_CREATE',
  UPLOAD_DELETE = 'UPLOAD_DELETE',
  UPLOAD_READ = 'UPLOAD_READ',

  // DOCUMENTS
  DOCUMENT_UPLOAD = 'DOCUMENT_UPLOAD',
  DOCUMENT_REVIEW = 'DOCUMENT_REVIEW',
  DOCUMENT_HISTORY = 'DOCUMENT_HISTORY',

  // OPERATIONS
  OPERATION_CREATE = 'OPERATION_CREATE',
  OPERATION_UPDATE = 'OPERATION_UPDATE',
  OPERATION_DELETE = 'OPERATION_DELETE',
  OPERATION_RESERVE = 'OPERATION_RESERVE',
  OPERATION_PROCESS = 'OPERATION_PROCESS',
  OPERATION_FINISH = 'OPERATION_FINISH',
  OPERATION_CANCEL = 'OPERATION_CANCEL',
}