//shared\src\enums\publicacion-status.enum.ts
export enum PublicacionStatus {
  BORRADOR = 'BORRADOR',
  EN_REVISION = 'EN_REVISION',
  OBSERVADA = 'OBSERVADA',
  RECHAZADA = 'RECHAZADA',
  PUBLICADA_NO_VERIFICADA = 'PUBLICADA_NO_VERIFICADA',
  PUBLICADA_VERIFICADA = 'PUBLICADA_VERIFICADA',
  PAUSADA = 'PAUSADA',
  ELIMINADA = 'ELIMINADA',
}