// shared\src\enums\user-type.enum.ts
export enum UserType {
  PARTICULAR = 'PARTICULAR',

  INMOBILIARIA = 'INMOBILIARIA',
  CORREDOR = 'CORREDOR',
  MARTILLERO = 'MARTILLERO',
  BROKER = 'BROKER',

  DESARROLLADOR = 'DESARROLLADOR',
  CONSTRUCTOR = 'CONSTRUCTOR',

  ARQUITECTO = 'ARQUITECTO',
  DECORADOR = 'DECORADOR',
  TASADOR = 'TASADOR',
}